### ISSUE TITLE
TileJSON file too large?

### ISSUE THREAD

**Issue by jliebrand** [mapbox/tippecanoe#450]
I've produced an mbtileset using tippecanoe 1.22.0 like i've done in the past, but uploading it to mapbox gives me this error:

Metadata exceeds limit of 60kb | The TileJSON file in your MBTiles upload contains too much information. | Remove extra or unneeded content from the TileJSON file (inside the MBTiles file).

a- what is the metadata? (I noticed in the release notes that there is additional stats in there?)
b- how can I inspect it?
c- (the answer to b probably answers this also, but) how can i update/modify/slimline/delete the metadata?

**Comment by ericfischer** [comment]
The additional metadata is a list of the most common values for each attribute, described in https://github.com/mapbox/mapbox-geostats

You can see what it looks like by using `tippecanoe-decode` or, in sqlite3, `select * from metadata where name='json';`.

I'll add a flag not to generate it, and will inquire about getting the 60K limit raised.

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/451 will add an option not to produce the tilestats.

**Comment by jliebrand** [comment]
Ah great, thanks! Any idea how i can fix up the existing mbtileset I created? (it took a day to produce, would be a shame to have to redo it ;-))

(well, I would only have to reproduce the tippecanoe part, but still that's 40 minutes plus waiting for #451 , so if there's a way to fix it up now that'd be handy)

**Comment by ericfischer** [comment]
You should be able to use `tile-join --no-tile-stats -o copy.mbtiles original.mbtiles` to copy the tiles to a new tileset with no tilestats.

**Comment by jliebrand** [comment]
sweet, thanks!

**Comment by jliebrand** [comment]
hmm 
tile-join: unrecognized option '--no-tile-stats'
?

**Comment by ericfischer** [comment]
You need the version of tile-join from https://github.com/mapbox/tippecanoe/pull/451

**Comment by jliebrand** [comment]
ah.. doh.. ok, will grab that

**Comment by jliebrand** [comment]
Great, that seems to have done the trick!  I noticed you mentioned the processing will be faster *with* the stats. So I guess it would indeed be good to get the limit increased, but for now this solves my problem; thanks

**Comment by ericfischer** [comment]
Glad it worked! Yes, the reason for generating tilestats in Tippecanoe is that doing it on the server side is a frequent source of timeouts with large tilesets.

**Comment by mapsam** [comment]
Hi @jliebrand - thanks for raising this! We're working on a fix to our uploader to avoid including the tilestats object in the size calculation. Will report back when we have a fix deployed.

**Comment by mapsam** [comment]
@jliebrand we've deployed a fix to our uploader that no longer counts the `tilestats` object against the length of the metadata object. Please try uploading again, and let us know if it's looking 👍 or 👎. 

Thanks to your issue, we also noticed we were appending tilestats to the TileJSON object on our servers unknowingly, which has also been resolved. Many thanks for raising this!

@ericfischer feel free to close this when you're ready.

**Comment by ericfischer** [comment]
Thanks @mapsam! The Tippecanoe changes are now released in https://github.com/mapbox/tippecanoe/releases/tag/1.22.1.

**Comment by wboykinm** [comment]
@mapsam Do you know if the max tilejson size for the uploads API [was ever increased from 64k?](https://github.com/mapbox/tippecanoe/issues/450#issuecomment-322532048)

Even after your [fix that doesn't count `tilestats`](https://github.com/mapbox/tippecanoe/issues/450#issuecomment-322879870), I'm still getting this:

![image](https://user-images.githubusercontent.com/735463/126836770-33834b50-beb5-4cdf-b804-8bc2c6fa131e.png)

The culprit appears to be the `generator_options` tilejson object, which is holding a history of some very verbose commands.

**Comment by wboykinm** [comment]
@mapsam Aaaaaaaaaactually we're cool! I was able to clear out the necessary metadata space and then the upload worked perfectly!

`sqlite3 tmp/dotmap_usa_20210725.mbtiles "DELETE FROM metadata WHERE name = 'generator_options'"`

Sorry for the false alarm!
