### ISSUE TITLE
Feature offset ?

### ISSUE THREAD

**Issue by iije** [mapbox/tippecanoe#968]
Hi, I notice that my area features that I generated to mbtiles has an offset in their positioning when viewed closeup. Is this normal?

`tippecanoe -f --no-tile-size-limit --no-simplification-of-shared-nodes --no-tiny-polygon-reduction --no-line-simplification --minimum-zoom=18 --maximum-zoom=18 -o /tippecanoe/Land.mbtiles /tippecanoe/Land.geojson`

![a](https://user-images.githubusercontent.com/112961944/225060677-b946fcf3-a798-4c02-aaa2-33fecb5fd456.jpg)

**Comment by iije** [comment]
Same goes of line features.

`tippecanoe -f  --no-tile-size-limit --no-simplification-of-shared-nodes --no-tiny-polygon-reduction --no-line-simplification --minimum-zoom=18 --maximum-zoom=18 --no-line-simplification -o /tippecanoe/road.mbtiles /tippecanoe/road.geojson`

![b](https://user-images.githubusercontent.com/112961944/225071207-c9231e29-4356-4f78-b5e1-67251505cdc9.JPG)

**Comment by e-n-f** [comment]
This should be fixed (or at least should be evenly distributed instead of always down and to the right) in the Felt version of Tippecanoe via https://github.com/felt/tippecanoe/pull/60

**Comment by iije** [comment]
Thank you. I am very new to docker and tippecanoe. I manage to run morlov/tippecanoe in docker but I am unable to get the others to work. Are you able to advice on what I can do to get the Felt version of tippecanoe to work on windows.

**Comment by iije** [comment]
i tried using metacollin/tippecanoe in docker.

`docker run -it --rm -v c:/tippecanoe:/tippecanoe metacollin/tippecanoe:latest tippecanoe -pn -f -o /tippecanoe/Land.mbtiles /tippecanoe/Land.geojson`

Which i still get the same offset.
![aa](https://user-images.githubusercontent.com/112961944/227685101-9f02595f-f69a-4167-94c1-483c24dad5b9.JPG)
![bb](https://user-images.githubusercontent.com/112961944/227685153-c1dd87e7-a899-490a-8d1e-90827c9df9f0.JPG)
